
net = "testnet"

mysqlUrl = "root:123456@/sea_test?charset=utf8&loc=Local&parseTime=true"

seeds = [
    'http://seed1.neo.org:20331',
    'http://seed2.neo.org:20332',
    'http://seed3.neo.org:20332',
    'http://seed4.neo.org:20332',
    'http://seed5.neo.org:20332',
    'https://test1.cityofzion.io:443',
    'https://test2.cityofzion.io:443',
    'https://test3.cityofzion.io:443',
    'https://test4.cityofzion.io:443',
    'https://test5.cityofzion.io:443'
]

NeoUrl = "https://test3.cityofzion.io:443"

[log]
    outputWay = "console"  # "console" or "file"
    output = "./seago.log" # required only outputWay = "file"